### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [DevFestVienna/devfest-at-site#11]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/DevFestVienna/devfest-at-site/blob/master/package.json#L9

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by helmuthb** [comment]
Thanks @DanielRuf! 🙂
I removed it now in 28078a603faef9924cefd9b439658c99a6bbd9e6
